<?php

namespace Database\Seeders;

use App\Models\Vacant;
use Illuminate\Database\Seeder;

class VacantsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $data=[
            [
                'author' => 'Karina',
                'title' => 'Auxiliar de centro de distribución',
                'city' => 'Bogotá cll 196 con auto norte',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'cedi',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Auxiliar de centro de distribución',
                'city' => 'Siberia parque siemens',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'cedi',
                'filtro' => '0',
                'job'=>'1'
            ],



            [

                'author' => 'Karina',
                'title' => 'Jefe de selección',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [      
                'author' => 'Karina',
                'title' => 'Analista de selección',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Especialista de comunicaciones',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Analista de contabilidad',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Analista de finanzas',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Auxiliar Administrativo',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Auxiliar de inventario',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Manager  comercial',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Coordinador de CRM',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [

                'author' => 'Karina',
                'title' => 'Desarrollador de aplicaciones',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [

                'author' => 'Karina',
                'title' => 'Auxiliar de Visual Merchandising',
                'city' => 'Ibagué- Santamarta',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Coordinador de planeación',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Analista de selección y formación',
                'city' => 'Siberia',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [

                'author' => 'Karina',
                'title' => 'Fotógrafo',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Karina',
                'title' => 'Auxiliar de contabilidad',
                'city' => 'Bogotá',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'administrativo',
                'filtro' => '0',
                'job'=>'1'
            ],


            [

                'author' => 'Sofia',
                'title' => 'Asesor de ventas',
                'city' => 'Tiendas a nivel nacional',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'comercial',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                
                'author' => 'Sofia',
                'title' => 'Mercaderista',
                'city' => 'Canal tradicional y grandes superficial a nivel nal',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'comercial',
                'filtro' => '0',
                'job'=>'1'
            ],
            [
                'author' => 'Sofia',
                'title' => 'Auxiliar integral',
                'city' => 'Bodegas de nuestras tiendas a nivel nacional',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'comercial',
                'filtro' => '0',
                'job'=>'1'
            ],
            [

                'author' => 'Sofia',
                'title' => 'Lider de tienda',
                'city' => 'Tiendas a nivel nacional',
                'description' => 'Sin descripción',
                'state' => '1',
                'salary' => '0',
                'experience' => 'Sin experiencia',
                'num_vacants' => '1',
                'num_aplic' => '0',
                'education' => 'Ninguno',
                'language' => 'Ninguno',
                'availability_travel' => 'si',
                'type_contract' => 'obra o labor',
                'type_cv_id' => 2,
                'area' => 'comercial',
                'filtro' => '0',
                'job'=>'1'
            ],
            // [

            //     'author' => 'Karina',
            //     'title' => 'DBA',
            //     'city' => 'Bogotá',
            //     'description' => 'DBA en Oracle',
            //     'state' => '1',
            //     'salary' => '4000000',
            //     'experience' => 'Con mas de 2 años de experiencia en el cargo',
            //     'num_vacants' => '2',
            //     'num_aplic' => '2',
            //     'education' => 'Pregrado',
            //     'language' => 'Ninguno',
            //     'availability_travel' => 'no',
            //     'type_contract' => 'indefinido',
            //     'type_cv_id' => 2,
            //     'area' => 'administrativo',
            //     'filtro' => '3',
            //     'job'=>'0'
            // ],
            // [

            //     'author' => 'Karina',
            //     'title' => 'Analista contable',
            //     'city' => 'Bogotá',
            //     'description' => 'Se requirer analista contable con buena actitud',
            //     'state' => '1',
            //     'salary' => '2800000',
            //     'experience' => 'Minimo dos años de experiencia en el cargo',
            //     'num_vacants' => '2',
            //     'num_aplic' => '0',
            //     'education' => 'Pregrado',
            //     'language' => 'Ninguno',
            //     'availability_travel' => 'si',
            //     'type_contract' => 'obra o labor',
            //     'type_cv_id' => 2,
            //     'area' => 'administrativo',
            //     'filtro' => '2',
            //     'job'=>'0'
            // ],
        ];
        foreach ($data as $datas) {
            Vacant::create($datas);
        }

   
        
        
    }
}